openapi: 3.0.3

info:
  title: EMPIRE API
  version: '0.9'

components:
  schemas:

    Code:
      type: object
      properties:
        id:
          $ref: '#/components/schemas/Id'
        container:
          $ref: '#/components/schemas/Id'
        name:
          type: string
        texts:
          type: array
          items:
            $ref: '#/components/schemas/DocumentText'
      required:
        - name
        - texts
        - container

    CodeContainer:
      type: object
      properties:
        id:
          $ref: '#/components/schemas/Id'
        order:
          type: number
        codes:
          type: array
          items:
            $ref: '#/components/schemas/Code'
      required:
        - order
        - codes

    DocumentText:
      type: object
      properties:
        id:
          $ref: '#/components/schemas/Id'
        document_id:
          $ref: '#/components/schemas/Id'
        text:
          type: string
        first_word:
          $ref: '#/components/schemas/WordCoordinate'
        last_word:
          $ref: '#/components/schemas/WordCoordinate'
      required:
        - document_id
        - text
        - first_word
        - last_word

    Id:
      type: integer
      format: int64
      description: A unique identifier within the class of the specific object it is referencing

    File:
      type: object
      properties:
        id:
          $ref: '#/components/schemas/Id'
        type:
          type: string
          enum:
            - SOURCE_FILE
            - DEMO_FILE
        name:
          type: string
        ext:
          type: string
      required:
        - id
        - type
        - name
        - ext

    Project:
      type: object
      properties:
        Id:
          $ref: '#/components/schemas/Id'
        Year:
          type: int32
        Month:
          type: int32
        Name:
          type: string
        Description:
          type: string
      required:
        - Year
        - Month
        - Name
        - Description



    WordCoordinate:
      type: object
      properties:
        paragraph:
          type: integer
        sentence:
          type: integer
        word:
          type: integer
      required:
        - paragraph
        - sentence
        - word


paths:
  /file:
    post:
      responses:
        200:
          description: successful upload, returns uplaoded file
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/File'


